#!/usr/bin/with-contenv bash 

# install git if needed
if [ -z `command -v git` ]; then
    echo "**** PhoenixAdult metadata agent: installing git ****"
    apt-get install --no-install-recommends -y git
fi

# clone or update PhoenixAdult.bundle repo
plugindir="/config/Library/Application Support/Plex Media Server/Plug-ins"
if [ ! -d "$plugindir/PhoenixAdult.bundle" ]; then
    echo "**** PhoenixAdult metadata agent: not found, cloning ****"
    git clone https://github.com/PAhelper/PhoenixAdult.bundle "$plugindir/PhoenixAdult.bundle"
else
    echo "**** PhoenixAdult metadata agent: pulling latest update ****"
    git config --global --add safe.directory '/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle'
    git -C "$plugindir/PhoenixAdult.bundle" reset --hard
    git -C "$plugindir/PhoenixAdult.bundle" pull
fi
chown -R abc:abc "$plugindir/PhoenixAdult.bundle"
